version: '3.8'

services:
  taskella:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./data/sqlite.db
      - NEXT_PUBLIC_API_BASE_URL=https://your-domain.com/api
      - NEXT_PUBLIC_TELEGRAM_BOT_NAME=${TELEGRAM_BOT_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      # Сохранение данных SQLite между перезапусками
      - sqlite_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  sqlite_data:
    driver: local